### ISSUE TITLE
Documentation Site for BlitzListForm and BlitzTable are broken

### ISSUE THREAD

**Issue by robert-boulanger** [mesqueeb/blitzar#114]
At the moment [BlitzListForm](https://blitzar.cycraft.co/blitz-list-form/) just returns 404
Same with BlitzTable

**Comment by mesqueeb** [comment]
@robert-boulanger it works for me :O what's the issue you're seeing ?

**Comment by mesqueeb** [comment]
Let me know if you can reproduce it! 😅 

<sub>--<br />Blitzar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
