### ISSUE TITLE
For custom components how to using prop "label" ?

### ISSUE THREAD

**Issue by ronald-mz** [mesqueeb/blitzar#126]
I'm using Quasar with BlitzarForm, and want to use the `q-input` as a custom component.

However, Blitzar uses `label` to create its own label over the component. How would I pass `label` to the custom component rather than to Blitzar?

**Comment by ronald-mz** [comment]
Nevermind, dug through the other issues a bit more and found a solution [here](https://github.com/CyCraft/blitzar/issues/108#issuecomment-1029821615)

Best! And thanks for an awesome library!

**Comment by mesqueeb** [comment]
good luck!

<sub>--<br />Blitzar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
