### ISSUE TITLE
BlitzListForm with Quasar framework

### ISSUE THREAD

**Issue by damiankao** [mesqueeb/blitzar#130]
This is a sample schema I am using to display a BlitzListForm within a BlitzForm:

```
[
    {
        "options": [
            {
                "value": "1",
                "label": "1"
            },
            {
                "value": "2",
                "label": "2"
            }
        ],
        "id": "key1",
        "label": "key1",
        "component": "QSelect",
        "dense": true,
        "internalLabels": true,
        "outlined": true,
        "hint": "quasar hint"
    },
    {
        "id": "key2",
        "label": "key2",
        "component": "BlitzListForm",
        "schema": [
            {
                "options": [
                    {
                        "value": "a",
                        "label": "a"
                    },
                    {
                        "value": "b",
                        "label": "b"
                    }
                ],
                "id": "subkey1",
                "label": "source type",
                "component": "QSelect",
                "dense": true,
                "internalLabels": true,
                "outlined": true
            },
            {
                "id": "subkey2",
                "label": "source data",
                "component": "QInput",
                "dense": true,
                "type": "textarea",
                "internalLabels": true,
                "outlined": true
            }
        ]
    }
]
```

The expected behavior is that an q-select component is shown with 2 select options (1,2). And a BlitzListForm is displayed where each item in the array is defined by a q-select (options a,b) and a q-input value. 

The outer q-select with options 1,2 displays correctly, but the BlitzListForm only shows the form label (key2) without inner q-components. 

Is there a way to get this to work with Quasar?

**Comment by damiankao** [comment]
It turns out BlitzForm and BlitzListForm were not globally registered. I ended up just importing markRaw from Vue and used the locally registered components to make it work. 

Thanks for the great component.

**Comment by mesqueeb** [comment]
glad it worked!

<sub>--<br />Blitzar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
