### ISSUE TITLE
QSelect can not display label

### ISSUE THREAD

**Issue by gunners81** [mesqueeb/blitzar#131]
greetings,

i have a problem to display q-select options label, it always show value of options.
my workaround is to use default component select not QSelect, but it will lost quasar style/css

please guide me how use quasar QSelect "map-options" inside json schema

**Comment by mesqueeb** [comment]
Did you try adding `mapOptions: true,` ?

Please post some code snippets so I can help. : )

**Comment by gunners81** [comment]
{
        id: "role",
        label: "Role",
        component: "QSelect", // make sure it's registered in `quasar.conf.js`
        options: [
          { value: "", label: "Select one", disabled: true },
          { value: "3", label: "Admin JBR" },
          { value: "4", label: "Admin JTG" },
          { value: "5", label: "Admin JTM" },
          { value: "6", label: "Keuangan" },
        ],
        outlined: true,
        dense: true,
        emitValue: true,
        mapOptions: true,
      },

![Screen Shot 2022-04-17 at 19 39 16](https://user-images.githubusercontent.com/12673285/163714616-9216e59c-b507-4019-83d9-99af2fe4bd04.png)

**Comment by duurland** [comment]
Added a defaultValue, but your snippet works fine for me.
Please provide a full example if you're still facing the problem.
![Untitled](https://user-images.githubusercontent.com/22466178/175359118-94b361ca-16d3-4578-bf66-b8a67fbe2e45.png)

**Comment by mesqueeb** [comment]
@duurland thanks for looking into this! I really appreciate all the help. 

Let's close this until further communication from the original poster. : )

Ps: Will look into launching the dev server soon!
