### ISSUE TITLE
Issue with complex layouts

### ISSUE THREAD

**Issue by azapater** [mesqueeb/blitzar#144]
Hi! first of all, congratulations for such a great project! 

it ticks a lot of issues I've been facing when it comes to creating forms with other libraries I checked and discarded in the past. great job!

I've been playing around this weekend with the library and even though I love it, I'm facing a few issues trying to migrate a personal project when it comes to the layout of the form. 

I use quasar, and the webapp is 100% responsive for desktop and mobile. I use lots of cols and rows to use the space on desktop in the most optimal way and when you go to mobile, everything goes col-12/fullwidth. The forms also are split in different sections that adjust in position automatically. 

I attach a screenshot with a few examples so you can get a better idea. 

![Screenshot_2](https://user-images.githubusercontent.com/1220658/188310428-9b17c605-39f6-42e0-807e-f71aead4ab25.png)

I understand that is a very complex form to automate with a schema, but I tried a few things with no luck: 

1º Create the necessary divs layout in the schema itself and nest all the inputs in slots. The problem here is that as soon as an id is not in the root level of the schema, it doesn't get the value passed through the v-model.

2º Create different blizzforms objects in the template sharing the same v-model and having different schemas for each form. This one, even though it kind of worked to create the sections (couldn't make the fields to use specific col-X tho), I'm loosing the form actions functionality, which I think is a superb idea giving that out of the box. 

Not sure if this type of very customised forms are even achievable with the library and I'm asking for too much. 

Thanks!

**Comment by mesqueeb** [comment]
@azapater is it possible to just use 3 separate `<BlitzForm />` ? 
You could make 1 wrapper form component manually that houses these 3 BlitzForms

in this case does it solve your issue by using the `fieldClasses` prop and adding your `-col-` classes?

**Comment by azapater** [comment]
thanks for the quick reply. I will play around with this approach and let you know ;-)

**Comment by azapater** [comment]
I've been trying a few extra things, but I'm afraid I won't be able to migrate the forms as they are atm. One of the issues I'm facing is the style injected in the form slot to control the columnCount that messes up the quasar grid system, and being straight in the style tag it can't be overwritten. 

```
    <slot v-bind="{ schema: cSchema, formData, formDataFlat, updateField }">
      <div
        class="blitz-form__form"
        :style="`grid-template-columns:${' minmax(0, 1fr)'.repeat(
          columnCount
        )}; grid-gap: ${gridGap}`"
      >

```
I guess I could try to override the whole slot myself and adapt it to my needs but IMO I'm fixing a few problems to create some new ones :-) 

Thanks anyway! and keep up the good work! I'll follow this project closely.
