### ISSUE TITLE
Is library still being developed/supported? 

### ISSUE THREAD

**Issue by shershen08** [mesqueeb/blitzar#152]
First, thank you for creating this free and flexible form-generation library !

I've been looking forward to seeing examples of using blitzar + other frameworks, Quazar in particular for months' but nothing there yet
https://blitzar.cycraft.co/blitz-form/#frameworks

**Comment by abumalekFayed** [comment]
This library works perfectly with quasar just use any quasar component and set component props as your need if you ned samples you can use Vue 2 samples  it will work with Vue 3
https://blitzar0.web.app/docs/blitz-form#quasar-framework

**Comment by mesqueeb** [comment]
Blitzar is semi-supported. Personally I only use it on a few low-maintenance projects, so I'm not actively building new features. But all the source code is open and I'm open to any contributions from the community!
I'll also do security patches when requested! : )

Thanks @abumalekFayed for weighing in! Blitzar works perfectly with Quasar and Vue 3 indeed!

Here is the working test project:
https://github.com/CyCraft/blitzar/blob/production/example-projects/quasar/package.json

Any documentation PRs also highly appreciated!

<sub>--<br>Blitzar was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.</sub>
