### ISSUE TITLE
Blitzform not work whit async QSelect or any select components

### ISSUE THREAD

**Issue by vici0uz** [mesqueeb/blitzar#154]
QSelect not work inside BlitzForm schema, options is pased in schema, but change in options after filtering never show in select list

**Comment by mesqueeb** [comment]
I believe you have to make options a dynamic prop for it to be reactive. Can you try it.

**Comment by vici0uz** [comment]
> I believe you have to make options a dynamic prop for it to be reactive. Can you try it.

@mesqueeb i haven't try that before, but not work too

-  if options is a ref the listed options is ever empty. 
- If is an array it shows initial items but no items added later.

I check with vue dev tools and whit a DOM ref:
- both ref and array updates internally, but nothing changes in QSelect.
-  i try explicitly call  refresh() on DOM ref after pushed new items, but also not work.

**Comment by mesqueeb** [comment]
Try making it a dynamic prop, there's documentation on this in the blitzar docs.

**Comment by vici0uz** [comment]
> Try making it a dynamic prop, there's documentation on this in the blitzar docs.

already try it... not work, nothing changes

**Comment by mesqueeb** [comment]
Can you share a code snippet ? I can try and have a look.

**Comment by vici0uz** [comment]
> Can you share a code snippet ? I can try and have a look.

[QSelect in BlitzForm schema](https://gist.github.com/vici0uz/4bc07b6f2b787c0d7f3e50e0526df6b7)

**Comment by vici0uz** [comment]
I put a standalone QSelect and a blitzar's QSelect side to side, with same ref() as options inside Standalone QSelect options is array of "Reactive" types but inside Blitzar QSelect options is array of "Object"

**Comment by mesqueeb** [comment]
Hey! It is probably because blitzform creates a copy of the schema passed to for performance reasons.
I had a look at your code, and can you try this?

https://gist.github.com/vici0uz/4bc07b6f2b787c0d7f3e50e0526df6b7#file-qselectblitzform-vue-L46

```ts
dynamicProps ['options'],
options: () => select_options_ref.value // change ref value but not options shown in component
```
When marking a prop as a dynamic prop, you have to pass it as a function. Please try this snippet and let me know!

Also, you had `dynamicPros` in your code snippet, while it is `dynamicProps` ;)

**Comment by vici0uz** [comment]
> ```ts
> dynamicProps ['options'],
> options: () => select_options_ref.value // change ref value but not options shown in component
> ```

That's work, thanks.
