### ISSUE TITLE
OptionGroup and Custom styling within blitzar and quasar

### ISSUE THREAD

**Issue by cherimo** [mesqueeb/blitzar#155]
Hi there, I have 2 questions within Quasar and Blitzar forms. I've looked around myself, but couldn't find a clear answer. For example, can I indicate within QOptionGroup what the maximum limit can be checked? Or do I have to work around this? I know that QSelect does have this option but I would prefer this in a checkbox form. And my 2nd question is to what extent can I customize the QInput and Qselect etc.. as indicated in the Quasar docs? For example custom template or icon?

I've read the documentation from Blitzar but I don't think it's quite complete in terms of styling and api capabilities.

**Comment by eric-nicular** [comment]
@cherimo Did you ever find answers to your questions?

**Comment by mesqueeb** [comment]
here's the quasar example
https://github.com/cycraft/blitzar/blob/51d32115d506f8e0ba456c5cab8c2ecdde06909e/example-projects/quasar/src/pages/BlitzFormExample.vue

you can do a radio list like so
```js
{
    id: 'powerUps',
    span: 1,
    component: 'QOptionGroup', // make sure it's registered in `quasar.conf.js`
    type: 'radio',
    defaultValue: () => [],
    label: 'Choose some power-ups',
    columnCount: 3,
    options: [
      { value: 'iso-8', label: 'Magic crystal' },
      { value: 'hp-potion', label: 'Health potion' },
      { value: 'energy-potion', label: 'Energy drink' },
    ],
  },
  ```
  I hope this helps.
