### ISSUE TITLE
Sending arrow functions in HTTPS responses?

### ISSUE THREAD

**Issue by eric-nicular** [mesqueeb/blitzar#158]
Can arrow functions and other programmatic syntax used by Blitzar be sent over HTTPS and parsed correctly for generating pages on the fly through the use of schemas?

As an example, could the part following "error" below be successfully sent as a string or some other format in a GET request's response and then used to generate a page's contents? Referring to: "(val) => (val === true ? null : 'You must accept our terms')"

{
    id: 'consent',
    label: 'Do you agree with our terms?',
    component: 'input',
    type: 'checkbox',
    defaultValue: false,
    dynamicProps: ['error'],
    error: (val) => (val === true ? null : 'You must accept our terms'),
  },

**Comment by mesqueeb** [comment]
I think this is similar to #117

The actual API request code is out of scope for the Blitzar library, but making sending functions is something that would be nice if provided.
