### ISSUE TITLE
extra context 

### ISSUE THREAD

**Issue by ahelal** [mesqueeb/blitzar#161]
Hi,

Thank you for blitzar. I have 5 independent blitzar form due to advanced layout i went down that path. I would like to build some conditional field across the 5 forms. 
As far as I know it is not possible since the formdata is separate. I am open to submit a PR to add extra context.

Would that be something your open to ? or you have any other ideas that might achieve same result ?

**Comment by mesqueeb** [comment]
I personally believe it's best to just keep the form data and schema separate.
but if you must you can just link any blitzform field to a global state instead, and not make it use `v-model`. So no need for an PR for this, as this work around is valid.
