### ISSUE TITLE
BlitzListForm - validation message

### ISSUE THREAD

**Issue by mitjarobic** [mesqueeb/blitzar#56]
Hello, 

how would I put a validation message under a quasar input field in a specific row? For example a second row.

Thanks.

**Comment by mesqueeb** [comment]
you can do so with rules eg.
```js
const schema = [
  {
    component: 'QInput',
    rules: [(val) => val.length > 3 || 'min 3 characters'],
  }
]
```
this should be possible as well for a list form

**Comment by mitjarobic** [comment]
Thank you. But I have an external validation so I need to set attributes on a field. Specifically 'error-message' and 'error' on QInput field. When I do that all rows get the same error message. I need to target only a specific row. For example the second one. How would I do that?

**Comment by mesqueeb** [comment]
Try this !
```js

evaluatedProps: ['error-message'],
errorMessage: (val, { rowIndex, formData }) => rowIndex === 2 ? 'an error' : '',

```

As you can see you can do the same thing for the error field and you can also access the formData for the entire row

**Comment by mitjarobic** [comment]
Thank you. I got what I needed in {$attrs} key .

**Comment by mesqueeb** [comment]
I think there might be a better option than accessing the $attrs key. Can you post your solution so I can have a look? 

The danger about the attrs key is that if I make internal changes you might not be able to get the same info as you do now.

**Comment by mitjarobic** [comment]
I am still using https://github.com/mesqueeb/quasar-ui-easy-forms. Haven't had time to update it yet.

`
errorMessage: (val, { $attrs }) => $attrs.rowIndex === 2 ? 'an error' : '',
`
