### ISSUE TITLE
Blitz table.

### ISSUE THREAD

**Issue by sanjaygyawali** [mesqueeb/blitzar#73]
Is quasar required dependency to be installed for  blitztable . I got the error  table is not defined in Qtable .

**Comment by mesqueeb** [comment]
I'm very sorry! The BlitzTable doesn't work yet outside of Quasar CLI apps. I plan to replace QTable with something that works everywhere and is not bound to a UI Framework with #66. However this will probably not be soon because I'm busy on some other projects.
Any help much appreciated!!

**Comment by sanjaygyawali** [comment]
Thank you
