### ISSUE TITLE
Class row in div component

### ISSUE THREAD

**Issue by josejachuf** [mesqueeb/blitzar#74]
Hi, this is my first day with blitzar. I use this with quasar framework.

I try do:

```
{
    span: 1,
    label: 'Test',
    component: 'div',
    componentStyle: 'border: solid thin goldenrod; padding: 0.5em',
    class: 'row',
    slot: [
      {
        component: 'div',
        slot: 'AAA',
        class: 'col bg-red'
      },
      {
        component: 'div',
        slot: 'BBB',
        class: 'col bg-blue'
      },
      {
        component: 'div',
        slot: 'CCC',
        class: 'col bg-orange'
      }
    ]
  },
```

I get this:

```
<div rules="" class="blitz-field__component" style="border: thin solid goldenrod; padding: 0.5em;">
  <div slot="AAA" class="col bg-red">AAA</div>
  <div slot="BBB" class="col bg-blue">BBB</div>
  <div slot="CCC" class="col bg-orange">CCC</div>
</div>
```

And I hope to get the **row** class in the first div 

```
<div rules="" class="row blitz-field__component" style="border: thin solid goldenrod; padding: 0.5em;">
  <div slot="AAA" class="col bg-red">AAA</div>
 
</div>
```

Consequently I see the divs stacked instead of seeing them in columns 

Jose

**Comment by josejachuf** [comment]
Doing this I get what I want.

Using componentClasses, but only in first div, in the internal div I keep using class. If replacement class by componentClasses stops working 
```
{
    span: 1,
    label: 'Test',
    component: 'div',
    componentStyle: 'border: solid thin goldenrod; padding: 0.5em',
    componentClasses: 'row',
    slot: [
      {
        component: 'div',
        slot: 'AAA',
        class: 'col bg-red'
      },
      {
        component: 'div',
        slot: 'BBB',
        class: 'col bg-blue'
      },
      {
        component: 'div',
        slot: 'CCC',
        class: 'col bg-orange'
      }
    ]
  },
```

**Comment by mesqueeb** [comment]
@josejachuf yes, you've correctly deduced the correct schema in this case!
you need to use componentClasses, because it's what will be used on your component, in this case the `div`. Because `class` is what's applied to the outer class, which is the div with the label etc.

The inner components inside a `slot` have slightly different behaviour, because they do not render fields with labels, but the direct component you define. That's why on those inner divs you can use `class` directly.

It's a bit getting used to, I agree. : S
If you have any suggestions for syntax improvement, let me know!

**Comment by ymarcon** [comment]
I am resurrecting this discussion because I wonder whether a fully functional field (labels, component etc) could be placed in a `slot`? That would be great for fine tuning the "layout" of a form.

**Comment by mesqueeb** [comment]
It depends on what exactly you want to do/achieve.

I feel a little bit that complex fine tuning requirements most of the time lead to very complex schema's, so you're usually better off writing  your own custom form in a Vue file without Blitzar in that case. 

But I'm still interested in hearing your exact use case or what you are trying to build. @ymarcon

**Comment by ymarcon** [comment]
My use case is about separating the form logic (definition of the fields, visibility condition, validation) from its "layout": advanced users (eg interviewer) with a large screen would prefer to have all fields in a single page for efficiency (and then the layout needs to be as compact as possible with a responsive grid), whereas regular users (eg respondent) would need more guidance, with a multi-page form and one or few fields per page. A "printable" rendering is also another possible layout. Depending on the context, the Blitzar form's schema would be generated to match the desired layout. 

Then in place of using the quite limited `span` property for instance, being able to place fields inside any `slot` would be a great improvement in that regard. Note that I am not expecting having a "layout" concept in Blitzar, just having the possibility to implement it would be great.

**Comment by mesqueeb** [comment]
@ymarcon sounds like a cool concept. In this case I'd rather improve the layout features of Blitzar than allowing any component to render in `slot`.   : )

Working with `slot` gets complex fast to support in all use cases, and it will potentially open up the door to a bunch of edge cases I gotta go fix then... 😅 

I'm interested however to give Blitzar better layout tools.

I'd like to ask you to please read this post:
https://github.com/CyCraft/blitzar/issues/8#issuecomment-815372546

and offer any thoughts and ideas in that thread. : )
