### ISSUE TITLE
How to span fields of blitz list form to multiple row ?

### ISSUE THREAD

**Issue by sanjaygyawali** [mesqueeb/blitzar#75]
Current Arrangement : 
[ a, b, c ],
[ a, b, c ],
[ a, b, c ],

Required Layout :
[
    a, b,
    c
],
[
    a, b,
    c
],
[
    a, b,
    c
],

**Comment by mesqueeb** [comment]
Yes it's possible with { span }I'll come back here late tonight to give more info.

**Comment by sanjaygyawali** [comment]
@mesqueeb Have you got time to see on this ?

**Comment by mesqueeb** [comment]
@sanjaygyawali Sorry I had forgotten about it.

I have created an example for you of how this can be done.
Please check the new documentation:

https://blitzar.cycraft.co/docs/blitz-list-form#multirow-example
