### ISSUE TITLE
Label Slot repeat in BlitzListForm

### ISSUE THREAD

**Issue by XiongLiding** [mesqueeb/blitzar#78]
Try to append a red star sign with label slot (for figure out required field), then it appears in every row.
Is it on purpose? If label only show once, maybe label slot shoud too.

Another problem: if set rules property (not empty) on QInput with outlined, result double outline.

![CleanShot 2021-06-17 at 13 36 23@2x](https://user-images.githubusercontent.com/679318/122337628-2c837980-cf71-11eb-88b2-69a3945db062.jpg)

````
[
  {
    "id": "basic",
    "label": "基本信息",
    "component": "BlitzListForm",
    "schema": [
      {
        "component": "QInput",
        "type": "text",
        "id": "name",
        "label": "姓名",
        "outlined": true,
        "dense": true,
        "rules": [ v => !!v || '必填' ],
        "slots": {
          "label": {
            "component": "span",
            "slot": "*",
            "style": "color: red"
          }
        },
        "options": [],
        "hideBottomSpace": true
      },
      {
        "component": "QInput",
        "type": "text",
        "id": "age",
        "label": "年龄",
        "outlined": true,
        "dense": true,
        "rules": [],
        "slots": {},
        "options": [],
        "hideBottomSpace": true
      },
      {
        "component": "QInput",
        "type": "text",
        "id": "time",
        "label": "时间",
        "outlined": true,
        "dense": true,
        "rules": [],
        "slots": {},
        "options": [],
        "hideBottomSpace": true
      }
    ]
  }
]
````

**Comment by mesqueeb** [comment]
@XiongLiding 
> If label only show once, maybe label slot shoud too.

Yes I agree. I overlooked this. Will fix.

> if set rules property (not empty) on QInput with outlined, result double outline.

This is also a bug. Fix coming.

**Comment by mesqueeb** [comment]
@XiongLiding I just released `0.0.29`, please try and let me know if these two issues are fixed

**Comment by XiongLiding** [comment]
I've tested. 
- outline fixed 
- label slot dose not.

`slot` should be `slots`. 
````
        const overwrites = {
          label: '',
          subLabel: '',
          slot: { label: undefined }, // <-- should be slots
        }
````

**Comment by mesqueeb** [comment]
@XiongLiding you're right 😅

**Comment by mesqueeb** [comment]
@XiongLiding please try 0.0.30 and let me know if it fixed it! ;)

**Comment by XiongLiding** [comment]
Thanks, It works now.
