### ISSUE TITLE
Is compatible with Quasar 2?

### ISSUE THREAD

**Issue by hermesalvesbr** [mesqueeb/blitzar#79]
Great project! I know about this project yesterday, congratulations about this idea.

This project, is compatible with new Quasar 2?

**Comment by mesqueeb** [comment]
@hermesalvesbr not yet!
I have plans to make Blitzar compatible with Vue 3 and Quasar 2 within the next 3-6 months. I'm slowly working on it. : )

You can follow this issue for updates
https://github.com/CyCraft/blitzar/issues/55
