### ISSUE TITLE
BlitzListForm Auto populates the next empty row conflict with required filed

### ISSUE THREAD

**Issue by XiongLiding** [mesqueeb/blitzar#80]
When you fill any required filed, there will show next row, which also have required field, make the form can't be submit.
need a config to stop auto populate and an function `addRow` just like `deleteRow`

**Comment by mesqueeb** [comment]
Can you give me the schema you're using ?

**Comment by XiongLiding** [comment]
I found the problem, the required's default tip is in English, I need locale it, so I customize my required function use rules, Maybe that's the reason.

The good news is that I aleady implement add/remove function without modify the BlitzListForm source code.

Set BlitzListForm's maxRows to 1, then add an `add` button.
```
            {
              component: 'QBtn',
              events: {
                click: (_e, component) => {
                  const { value, schema } = component.$parent;
                  const emptyRow = schema.reduce((carry, { id }) => ({ ...carry, [id]: undefined }), {});
                  let newValue = value.length ? value : [emptyRow];
                  console.log(newValue);
                  newValue.splice(component.rowIndex + 1, 0, emptyRow);
                  component.$parent.$emit('input', newValue);
                },
              },
              round: true,
              span: '30px',
              size: 'sm',
              icon: 'add',
              color: 'positive',
            },

```

![49beb2a1fa61a82962b80db7f3050725](https://user-images.githubusercontent.com/679318/126895103-bbeb8800-c090-4e14-92f9-d98fdb547c17.gif)
