### ISSUE TITLE
showCondition does not clean form data

### ISSUE THREAD

**Issue by ymarcon** [mesqueeb/blitzar#82]
Hi,

In the [Show or Hide a Field Based on Another Field](https://blitzar.cycraft.co/docs/blitz-form#show-or-hide-a-field-based-on-another-field):
* select the checkbox
* enter data in the input fields that appeared
* deselect the checkbox

=> `formData` still contains the input data, which are then invalid

**Comment by mesqueeb** [comment]
@ymarcon thanks for your post. 

Can you post your full schema here?
I want to check your schema where the showcondition is set, and what controls that condition.

I have some ideas that I think can help you. 

The main idea is to clear the field with the `fieldInput` helper function when you hide/show the field.

**Comment by ymarcon** [comment]
I have just used the online demo (see the link). I guess there is a workaround as you suggested, but I think it should be a built-in feature otherwise unexpected data will be collected. It is more than a "show" condition, it should really be part of the data schema.

**Comment by ymarcon** [comment]
For the record, I was able to workaround with the `updateField` function.
