### ISSUE TITLE
Misusage of disabled HTML attribute

### ISSUE THREAD

**Issue by ymarcon** [mesqueeb/blitzar#83]
I am playing with v1.0.0 branch + quasar. It appears that options, toggle, slider etc components are in the disabled state despite the blitzar form mode is 'edit'. It is because the `disabled` HTML attribute is misused: the statement `disabled="false"` is not valid because what matters is the presence or not of this attribute. Then whatever the value is assigned to `disabled`, the component will be in the disabled state. See [MDN HTML disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). 

The same goes with the `required` attribute. And also you cannot have `disabled` and `required` at the same time.

**Comment by mesqueeb** [comment]
@ymarcon good catch! I will fix it asap

**Comment by ymarcon** [comment]
Any update about this issue? Could you show me where these attributes are handled in the code?

**Comment by mesqueeb** [comment]
@ymarcon haven't gotten around to it yet : S

Here you find the source code of BlitzField where we would need to update the label elements:

https://github.com/CyCraft/blitzar/tree/v1.0.0/packages/form/src/components

**Comment by ymarcon** [comment]
Could you give me some guidance for setting up the development flow? I have tried with `npm run dev:vue-cli` but the vue app is broken. How do you proceed?

**Comment by mesqueeb** [comment]
@ymarcon I have cherry picked only your last commit and merged it into `1.0.0`.
Thanks for separating those!

I will try to improve documentation on the development flow and how you can help out going forward. It's a bit messy now because of the transition, but will definitely cleanup after releasing 1.0!

**Comment by mesqueeb** [comment]
@ymarcon released on `@next`
please install with
```
npm i @blitzar/form@next
```
https://www.npmjs.com/package/@blitzar/form
