### ISSUE TITLE
Suggestion: Submit Blitzar to vuejsexamples?

### ISSUE THREAD

**Issue by jasonfharris** [mesqueeb/blitzar#94]
I didn't see Blitzar in https://vuejsexamples.com/ under form. Blitzar is a lot nicer than the other form generators I saw on this list. You might want to submit it?

**Comment by mesqueeb** [comment]
@jasonfharris thank you so much for your kind words!

Would you be able to help me putting it on there for me? 😊

**Comment by jasonfharris** [comment]
There is the https://vuejsexamples.com/submit-project/ link at the bottom of the page. The submission is probably best coming from the author? Again thanks for Blitzar!

**Comment by mesqueeb** [comment]
@jasonfharris thanks! I've emailed ;) let's see

**Comment by mesqueeb** [comment]
@jasonfharris they released it! 🎉

**Comment by mesqueeb** [comment]
https://vuejsexamples.com/generate-vue-forms-and-data-tables-fast-with-a-simple-json-like-syntax/
