### ISSUE TITLE
validateFormPerSchema ignoring required = false

### ISSUE THREAD

**Issue by rdemo** [mesqueeb/blitzar#96]
Possible bug, or possibly I am missing something, but even if I set "required" = false, the validateFormPerSchema routine comes back requiring it still.

Here is my code... 

In the schema: 

{
          id: 'familyPostalCode',
          component: 'QInput',
          subLabel: 'Postal Code',
          errorFieldName: 'Postal Code',
          emitValue: true,
          dense: true,
          showCondition: true,
          required: false
        },

const result = validateFormPerSchema(formData, this.schema)

In the output...

familyAddress: null
familyBarangay: "Field is required"
familyCity: null
familyCountry: null
familyName: null
familyPostalCode: "Field is required"
familyProvince: null

Thanks for any help.

**Comment by mesqueeb** [comment]
@rdemo should be fixed on latest: `blitzar@1.0.13` (i hope you're not on the vue 2 version... 😅 )
can you test and let me know if this helped? : ) 

<sub>--<br />Blitzar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance. </sub>

**Comment by mesqueeb** [comment]
btw, for pasting code into github issues, next time don't forget to add this above your code blocks: ```js

and at the end close with ```

**Comment by rdemo** [comment]
Yes!  That fixed it!  Thank you.

I've not posted much on github, thank you for letting me know about the ```js and ```.  I'll remember that next time.

Thanks again for such a quick response.
